### PR TITLE
Add ReplaceString method with tests

### PR DESCRIPTION
**Pull request by WebWat**
Add ReplaceString method to replace old strings with new strings a certain number of times.

### CODE REVIEW

**Review by ardalis — COMMENTED** [review]
What are some scenarios in which this would useful?

**Comment by WebWat** [comment]
For example, if you have a string where you want to replace only part of the similar data, rather than all of it, as the standard String.Replace method does.

**Comment by ardalis** [comment]
Ok, given that scenario, another way you might want to do it would be within a certain range of the input string, right? Like, replace all occurrences in the first 100 (original) characters of the input string?

Alternately replace all instances of X until you come to an instance of Y.

Just trying to think of different variations on your idea of replacing strings, but only up to a certain point.

Also, apologies but I re-organized the code - could you please resolve conflicts and I will approve? If you want to add anything related to the variants I just mentioned, feel free. You can put them in the StringManipulationExtensions.cs file in the Strings subfolder/namespace at this point, please. Thanks!

**Comment by WebWat** [comment]
Thank you for your comment. I will definitely try to look into other ways of implementing this method.

**Comment by ardalis** [comment]
I didn't mean instead of your way - I meant in addition to, perhaps as overloads or just other extensions. In case that wasn't clear.

**Comment by WebWat** [comment]
All right, I hear you.

**Pull request closed without merging**
