### PR TITLE
Seb stian main

### LINKED ISSUE #20: Add string.Reverse extension
Self-explanatory, adds new extension method for `string` that reverses it. For example: `"abc"` → `"cba"`

I would be happy to work on this.

### PR DESCRIPTION
**Pull request by ShadyNagy**
Fix conflict on PR #24 & Fix #20

### CODE REVIEW

**Comment by ShadyNagy** [comment]
@ardalis and @Seb-stian 
Is there any other way I can fix the conflict (by a commit to the original PR #24 ) ?

**Comment by Seb-stian** [comment]
I will be able to do that myself tomorrow if that's ok. Not sure if I can help otherwise atm.

**Comment by Seb-stian** [comment]
Your changes are well done though. If you are able to apply them, please, go ahead.

**Comment by ShadyNagy** [comment]
will close as @Seb-stian change his PR thanks ;)

**Pull request closed without merging**
